name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint with KtLint
      run: ./gradlew ktlintCheck


  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Run the Gradle Build
        run: ./gradlew build -x test
      - name: Archive Jar with Dependencies
        uses: actions/upload-artifact@v2
        with:
          name: Jar with Dependencies
          path: build/libs

  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Test with Gradle
        run: ./gradlew test --tests "*"
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test
      - name: Archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage report
          path: build/reports/jacoco/test/html
          
  documentation: 
    runs-on: ubuntu-latest
    needs: test
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v2
      
      # Runs the Gradle dokkaHtml task
      - name: Dokka with Gradle
        run: ./gradlew dokkaHtml
      
      # Builds a zip file with the KDoc generated website in it 
      - name: Archive KDoc Documentation
        uses: actions/upload-artifact@v2
        with:
          name: KDoc Documentation Site
          path: build/dokka/html
         
